# Generated by Django 4.2.20 on 2025-05-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0006_alter_userprofile_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='college_id',
            new_name='roll_no',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
