# Generated by Django 4.2.20 on 2025-05-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0008_test_testattempt_mcqquestion_testresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together=set(),
        ),
    ]
